# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a87e785ccedd85f930020248a858c2d097e91621c36509f9debe223e5e1ced97a933f575ebf7d0d59f4def2d192f9bdddc42e7cce738e2f541f1526c4bbf4e6

test:
  secret_key_base: 77e54e58b6ce2b42f0dbbcc606144bb445f986525647c8544970300451e29239d520781f44166da8c7b64a7b43a71a7df6bd6d1281fd80d29e533cc843d89644

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
